CREATE TABLE "podft".subjects (
	subject_id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
	subject_type int,
	subject_number_in_list int NULL,
	subject_inn varchar(20),
	subject_snils varchar(20),
	subject_category varchar(5) NULL,
	subject_fio varchar(100) NOT NULL,
	subject_birthday date NULL
);
CREATE table "podft".documents(
 doc_id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
 owner_id int references "podft".subjects(subject_id)  on delete CASCADE,
 doc_type varchar(150),
 doc_ser varchar(10),
 doc_number varchar(20),
 doc_organ varchar(301),
 doc_date_begin date
)

CREATE table "podft".list_info(
 list_id int GENERATED BY DEFAULT AS identity PRIMARY KEY,
 Format_version varchar(5),
 list_date date,
 list_prev_date date
)
